version: '3.9'

services:
  backend:
    build: ./backend
    container_name: cctv_backend
    env_file:
      - .env.example
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: cctv_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongodb:
    image: mongo:7
    container_name: cctv_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
